default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: nordic_sns_development

test:
  <<: *default
  database: nordic_sns_test

production:
  <<: *default
  database: nordic_sns_production
  username: nordic_sns
  password: <%= ENV['NORDIC_SNS_DATABASE_PASSWORD'] %>
